language: python
install:
    - pip install enum34
    - pip install typing
    - pip install pathlib
    - pip install vim-vint
script:
    - vint syntax/ats.vim
    - vint ftdetect/ats.vim
    - vint ftplugin/ats.vim
